### ISSUE TITLE
The README file does not describe the project's goal/features at all

### ISSUE THREAD

**Issue by ghost** [MagpieTeam/router#9]
That's a bit inconvenient ;-)

**Comment by trarbr** [comment]
You're right! 

This project is part of a final computer science project. We're doing it on behalf of DTU Risø (technical university of Denmark). This "router" is supposed to play a part in their next-generation sensor-data-collection platform. Basically, "loggers" are connected to sensors, and send measurements from the sensors to the router. The router is built with Phoenix, and does 3 things: stores measurements in Cassandra, aggregates measurements per minute and per hour and stores the aggregates as well, and broadcasts the measurements on Phoenix channels.

**Comment by ghost** [comment]
Well that surely sounds nice! data logging with embedded devices is always very interesting ;-)
Good luck and have fun!
